services:
    ms-compras:
    image: mscompra:v1.0
    container_name: ms-compra
    #depends_on:
    #  - ecommerce_app
    ports:
      - 5002:5000
    networks:
      - mired
    environment:
      - FLASK_CONTEXT=${FLASK_CONTEXT}
      - DEV_DB_URI=${DEV_DB_URI}

networks:
  mired:
    external: true