services:
  ms_catalogo:
    container_name: ms_catalogo
    ports:
      - "5001:5000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/proyecto_ms
      REDIS_URL: redis://redis:6379
    networks:
      - mired

networks:
  mired:
    external: true